### ISSUE TITLE
[Bug]: Refreshing page breaks page

### ISSUE THREAD

**Issue by sydneywalcoff** [hackforla/expunge-assist#1017]
### Overview
If you refresh any page that isn't the home page/landing page `expungeassist.org/`, it adds to the url in an endless loop. Here's an example:
`https://expungeassist.org/form/?/&/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/finalize`

### Action Items
This is likely related to the update we just made changing the way we route our app in #1002 

### Resources/Instructions
- React Router docs: https://reactrouter.com/en/main

**Comment by whitneywind** [comment]
@sydneywalcoff I'm still trying to work out exactly why this is happening, but since it only happens in prod, I haven't been able to actually test any solutions. It's definitely has to do with the router and its relationship to gh-pages. I'm going to try to replicate the router/gh-pages relationship in another project and see if it occurs there.
In the meantime I think we should revert to using the HashRouter. Especially since it seems that it's not only refreshes, but also any page other than the homepage that is accessed directly is getting this infinite loop problem.

**Comment by whitneywind** [comment]
@sydneywalcoff  Oh! And if I could know the PUBLIC_URL environment variable, or at least what form it's in that will help troubleshoot too

**Comment by sydneywalcoff** [comment]
Closing this issue as we've reverted the code causing this bug. We'll revisit in a different issue that address both.
