### ISSUE TITLE
design a loading page

### ISSUE THREAD

**Issue by sydneywalcoff** [hackforla/expunge-assist#1047]
### Overview
We have a loading screen, and it's ugly lol It happens quickly when people first come to our page. It's just the word 'loading...' really quickly in the corner and distracts from the flow of the rest of the website. Bonus points if you want to add a cute little animation. 

### Action Items
- [x] design the loading page/screen
- [ ] remove dependency from #1048 and move to ready for approval

### Resources/Instructions
[Here's a video](https://watch.screencastify.com/v/XlxbD9FUjsnTMXoVaJPr);
Reach out to Sydney if you have any questions.

**Comment by davidwiese** [comment]
@sydneywalcoff 

I finished up the design, and I was able to edit the colors on the GIF to match EA's purple theme instead of the blue one it came with:

![desktop](https://github.com/hackforla/expunge-assist/assets/21321101/1ff905f9-d24e-4dff-babb-ff4e41d0f8b2)

![mobile](https://github.com/hackforla/expunge-assist/assets/21321101/7c78192f-37c3-437c-9443-0778ba327d14)

Kind of stuck on how to implement it now. I still see a brief flash of "Loading..." where i've tried inserting it and had to simulate a long load time with a setTimeout function to test/style the page correctly.

Going to keep researching!
