### ISSUE TITLE
code loading page

### ISSUE THREAD

**Issue by sydneywalcoff** [hackforla/expunge-assist#1048]
### Dependencies
- [x] #1047
- [x] #1080

### Overview
We're updating our loading screen to be more aesthetically pleasing. 

### Action Items
- [x] Update our current loaded state to match the one above. 

### Resources/Instructions
- [Design - New Figma Link - Spinner Only](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=13955%3A6054&mode=design&t=9QD0Xyl5eZBAuxhD-1)
- [Design - Old Figma Link](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=13655%3A855&mode=design&t=ZZ3x4PywxQ4p0q1H-1)
- [GIF Link](https://lottiefiles.com/animations/man-working-F6Lb30nTpL)

**Comment by davidwiese** [comment]
@sydneywalcoff 

I finished up the design, and I was able to edit the colors on the GIF to match EA's purple theme instead of the blue one it came with:

![desktop](https://github.com/hackforla/expunge-assist/assets/21321101/1ff905f9-d24e-4dff-babb-ff4e41d0f8b2)

![mobile](https://github.com/hackforla/expunge-assist/assets/21321101/7c78192f-37c3-437c-9443-0778ba327d14)

Kind of stuck on how to implement it now. I still see a brief flash of "Loading..." where i've tried inserting it and had to simulate a long load time with a setTimeout function to test/style the page correctly.

Going to keep researching!

**Comment by davidwiese** [comment]
I was able to implement the loading page, but the page itself takes a moment to load (because of the animation). It kind of feels like it defeats the purpose of a smooth transition into the app. 

Using simulate throttling on both medium- and low-end mobile connections, the loading page itself also loads in pieces (first you see Loading and the spinner, then the header/logo, and finally the animation).

I wonder if we might have over-engineered this page and it should be simplified to load together instantly.


https://github.com/hackforla/expunge-assist/assets/21321101/c1a6f6f3-9780-4b3d-95f6-a90acc7aae3f

**Comment by davidwiese** [comment]
@sydneywalcoff That's actually the 'Loading' text on the LoadingPage component, not the original one we are trying to replace. It just renders before everything else (the spinner, header/logo, and animation).

We could use a static frame from the animation, or do away with it altogether. Will wait to hear back from you/design.

**Comment by jyehllow** [comment]
@davidwiese Made a new version with only the spinner + loading text

We have a design meeting later today, will update if there are any other opinions on this
