### ISSUE TITLE
Improving Visuals

### ISSUE THREAD

**Issue by ermbrown** [hackforla/expunge-assist#1079]
### Overview
We updated the the images to SVGs to appear clearer online, We also updated the language in the "Make letter writing less intimidating" section. Lastly we updated the colors of the numbers and the letter content and image quality. Reference Issue #980 

### Action Items

- [x] Update Involvement and Letter images to SVGs
- [x] Updated content to the letters and Making writing less intimidating sections

### Resources/Instructions
Reference issue #1079 in [Dev Team Page 210](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=13880%3A4917&mode=design&t=FUoatMjjxnFeIaQM-1)

SVG Link in [Improving Visuals](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=13895%3A3547&mode=design&t=gdj5UN29CPYc7zUq-1)

SVGs linked below

**Comment by sydneywalcoff** [comment]
@emmathrash can you export the assets and link them under the resources?

also the numbers you're referring to in the figma is also an image, can you include that with the other resources?

**Comment by ermbrown** [comment]
@sydneywalcoff Just added a link the the assets.

**Comment by ermbrown** [comment]
![Involvement Community Desktop](https://github.com/hackforla/expunge-assist/assets/130421855/94e376b2-f644-4712-aad1-e7a019cae66c)
![Involvement Community Mobile](https://github.com/hackforla/expunge-assist/assets/130421855/de218078-36fd-4240-9093-c360e95892ab)
![Letters Desktop](https://github.com/hackforla/expunge-assist/assets/130421855/7429b38e-3139-4c97-adbc-bcc8fcea8d69)
![Letters Mobile](https://github.com/hackforla/expunge-assist/assets/130421855/3bb4e4d6-50c8-4a61-9bc0-5b8f0f24f2da)

**Comment by davidwiese** [comment]
ETA: before 1/18/24 meeting

**Comment by davidwiese** [comment]
@sydneywalcoff @ermbrown 

Hi guys - here are some before/after screenshots with the screenshotExample and completeLetter .png files replaced with the .svg files. 

<details>
<summary>Visuals before changes are applied</summary>

![screenshotExampleBefore](https://github.com/hackforla/expunge-assist/assets/21321101/4c902d55-d6bb-427d-816f-b1f37fb2d02a)
![completeLetterBefore](https://github.com/hackforla/expunge-assist/assets/21321101/78767487-0aed-4ff4-b42e-749018b312f6)


</details>

<details>
<summary>Visuals after changes are applied</summary>

![screenshotExampleAfter](https://github.com/hackforla/expunge-assist/assets/21321101/7d0ec1e6-cb31-436f-820c-bbf44bd4b234)
![completeLetterAfter](https://github.com/hackforla/expunge-assist/assets/21321101/7a401208-8d67-4d30-bdc8-632f3f926048)


</details>

As you can see, there are some odd artifacts present with the svg files. In the screenshotExample, they are at the bottom of the Involvement bubble, and in the completeLetter, the side edges are really jagged.

One other thing to note for the "Updated number color" change - that entire section is a .png image, so I'm unable to just go in and change the color on the numbers. It also appears that the color of all the "How it works" text to the left of the numbers was changed from russian violet to black as well.

**Comment by anitadesigns** [comment]
Hey @davidwiese, thanks for bringing this to our attention and catching that! 

For the svgs coming out with jagged edges, it looks like it may be due to the drop shadow we added. We can export the illustrations as SVGs again without the drop shadow. Would it be possible to add the drop shadow on your end? If not, @jyehllow and I can keep exploring!

As for the "Updated number color" and updating the color for "How it works", please disregard. Seems like that was an oversight from my end as the font color should email russian violet until we finalize our color system. I'll go ahead and remove that change from under the "Action items" to this issue

**Comment by davidwiese** [comment]
Hi @anitadesigns!

I don't think it's possible for me to add drop shadows in really precise places once the SVG is generated. I can only apply it to the entire element once it is in the DOM. I think moving forward I will need finished files to drop in, and then I can make sure it is responsive and renders properly at different screen sizes.

Copy that on the color change!

**Comment by sydneywalcoff** [comment]
@anitadesigns David is right about adding dropshadow to nonconventional shapes. 

The easiest solution will probably to have the svg exported with the drop shadow and a square/rectangle transparent background just barely larger than the letter image.

**Comment by anitadesigns** [comment]
@jyehllow was able to fix the Letter images, but still working on fixing the Involvement image. @jyehllow can you export and upload those svgs here? 

@davidwiese we;ll get you the Involvement image once we figure it out!

**Comment by davidwiese** [comment]
@anitadesigns @jyehllow thanks!

**Comment by jyehllow** [comment]
![Large Letter SVG - v2](https://github.com/hackforla/expunge-assist/assets/75225741/bc1fcfee-74d5-4276-bf45-3ba5f3ea9e73)
![Small Letter SVG - v2](https://github.com/hackforla/expunge-assist/assets/75225741/355d814b-59ca-43c5-aae7-5e80c488a71e)
![Large Letter SVG - v3](https://github.com/hackforla/expunge-assist/assets/75225741/062c2f79-9d88-47ca-9d1e-3a7dd0168e54)
![Small Letter SVG - v3](https://github.com/hackforla/expunge-assist/assets/75225741/e26ed49a-b6b6-4dd3-8288-af5a03e7fc61)

Here you go @davidwiese! I made two versions of the fix for each one - one with a small 0.1px border of a really light color (v2), and a variation with just 1px extra width on each side (v3). Not sure if you have a preference for which one works better!

**Comment by anitadesigns** [comment]
@davidwiese I think I fixed these. Let me know if they don't work! I can keep working on it if it still exports incorrectly

![Small Involvement SVG](https://github.com/hackforla/expunge-assist/assets/105686896/b5e7b819-6ff8-46aa-b0e4-999310f67fec)
![Large Involvement SVG](https://github.com/hackforla/expunge-assist/assets/105686896/178a9b10-4d28-482a-bcb2-d6debeb3d74a)

**Comment by anitadesigns** [comment]
@davidwiese here are the Involvement screenshots! Lmk if they don't work

![Large Involvement SVG (1)](https://github.com/hackforla/expunge-assist/assets/105686896/37

![Small Involvement SVG (2)](https://github.com/hackforla/expunge-assist/assets/105686896/55eb07f4-6366-4529-b9af-5806d82133b2)
b3d494-d33e-4578-b5a9-2ba96283bb19)
