### ISSUE TITLE
Creating New Merged Team

### ISSUE THREAD

**Issue by amejiamesinas** [hackforla/expunge-assist#1122]
### Overview
During Org Meeting, ask Bonnie about creating merged team. 

### Action Items
- [x] Connect with Bonnie, add Sydney as Maintainer to new merged team

### Resources/Notes
https://github.com/orgs/hackforla/teams/expunge-assist-merge/members

**Comment by ExperimentsInHonesty** [comment]
@sydneywalcoff I created a Merge team https://github.com/orgs/hackforla/teams/expunge-assist-merge/members

Here are the settings in the website repo under Settings > Branches to use as an example
![screencapture-github-hackforla-website-settings-branch-protection-rules-21239485-2024-01-26-13_23_05](https://github.com/hackforla/expunge-assist/assets/37763229/1e0a8461-05da-43e5-87f9-3be156bdf704)

I am excited to hear that you're planning to use some of the automations from the website team... with the following caveats
1. we are in the process of refactoring all of them, so that they use a common variable file.  And all labels will go into this variable file, so that if we change the name slightly, we don't have to figure out which GHA has to be edited, we can edit directly in the variable file.  See this issue for more details https://github.com/hackforla/website/issues/5205
2. We actually planned on taking the automations from website team and turning them into org wide automations.  And this would be taken on after we revise all the GHAs on the website team.  I would prefer if we make them global, and then you deploy them on expunge-assist.  But that would involve waiting until the website team finishes their refactor, and then you becoming the lead of the migration to org wide (see currently proposal https://github.com/hackforla/engineering/issues/34), which I would be happy to supply as many developers as you need to do whatever issues you create.  

Let's have a meeting.  I am sending you a link via Slack to make a 1-on-1 meeting with me, and I will invite Roslyn (the current website dev lead) to it.
