### ISSUE TITLE
Create expungement process graphic

### ISSUE THREAD

**Issue by sylvia-nam** [hackforla/expunge-assist#1173]
### Overview
Create a graphic that represents the expungement process. The graphic will be used for the EA site post-Launch Prep, the Wiki, and internally.

### Action Items
- [x] First draft
- [x] Second draft of a mock-up. Design will draft mock-up that is consistent with the brand book
- [x] Discuss between Design x UXR to refine mock-up; discuss future uses and variations
- [ ] Finalize graphic 

### Resources/Notes
Here's the first [draft](https://docs.google.com/document/d/1m4jE8BjgEDWs47e8KtPYbg1y3m4Am4Dr/edit) of the mock-up

**Comment by sylvia-nam** [comment]
Amend: graphic is not right space for project One Sheet. Instead graphic can be used elsewhere: site or Wiki, etc.

**Comment by anitadesigns** [comment]
Developed a simple graphic of the process here with the current branding colors. Since the colors will probably be updated, the colors on this graphic will need to match as well. Also this graphic lays horizontally, which we may want to discuss having a vertical one depending on where we will use the graphic. 
![Frame 1034](https://github.com/hackforla/expunge-assist/assets/105686896/7fcfa27e-5e08-462d-9788-d4b5beadc6d7)


Image may not be fully visible with dark mode, so I am also attaching the 2nd draft of the graphic with a white background:
![Expungement Process](https://github.com/hackforla/expunge-assist/assets/105686896/49e42baf-c7d1-4d5d-a79b-69490aa9b9ad)


2nd draft of the graphic can be found [here](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=14972-3045&mode=design&t=fJwnNvbDR2UVisY1-4)

**Comment by sylvia-nam** [comment]
This looks great!

**Comment by anitadesigns** [comment]
@sylvia-nam made some edits correcting misspellings on the Figma draft. Also suggested it would be helpful to visually highlight step 2. 

Next iteration will include that highlight

**Comment by sylvia-nam** [comment]
Time for an update! Please comment the following update:
**Progress:** Ongoing: waiting for 3rd mock-up that shows where the letter fits in the process
**Estimated Time to Completion (ETC):** TBD

**Comment by raeraeicky** [comment]
@anitadesigns @sylvia-nam since there is one To Do left on this issue, I'll split that item out into a separate issue and move the rest to Done
