### ISSUE TITLE
Gang Injunction Wireframes 

### ISSUE THREAD

**Issue by j100892** [hackforla/expunge-assist#138]
### Overview

Based on our current research in the Google Drive on Gang Injunctions, could we create some early sketches or wireframes of how we could repurpose the statement generator designs to fit a letter people could use to get themselves off a gang injunction list? 

### Action Items

- [x] Identify opportunities to reuse designs for the injunction letter 
- [x] document with features or elements that would be needed in the designs 
- [ ] early wireframes or sketches for sharing

**Comment by anitadesigns** [comment]
This might be a more specific case and a different process folks have to take that differs from the expungement process. I was able to find this [website](https://www.lnlegal.com/criminal-defense/federal-crimes/gang-crimes/gang-injunctions/#:~:text=If%20the%20court%20does%20enforce,interview%20with%20a%20district%20attorney.) that explains a bit, but this would require more research. @SamHyler

**Comment by SamHyler** [comment]
> Excellent level

Interesting @anitadesigns. There are no links to where any of the work from this issue is, so feels a bit lost. In UXR we talk a lot about the possibility of using our product for multiple actions (even for all states has been researched). I don't know if it's relevant any longer, but perhaps pop it over to UXR for their acknowledgement that past work has been done on this so that they can possibly see if relevant and close. @yumengluo @daniellerubio
