### ISSUE TITLE
Team Updates for Bonnie Review

### ISSUE THREAD

**Issue by amejiamesinas** [hackforla/expunge-assist#1410]
### Overview
On Friday, June 14, Bonnie will be reviewing our product MVP, landing page, about us, FAQ's, etc. 
In preparation for her review, we would like to let her know what we have updated. 

For each team, please use this issue to identify 2 things: 
1) what updates did your team make in preparation for her review? (so we can let her know the major priorities we worked on)
2) any specific feedback you would like to request from Bonnie?  (if there is specific feedback we would like from her)

We will then use the information in this issue to provide Bonnie with instructions for her review. 

### Action Items
For each team, PM and/or lead please provide a response to questions 1 and 2 in the comments. Once complete please check off your team:
- [x] Design
- [x] Content
- [x] Research
- [x] Development

**Comment by emmathrash** [comment]
1. What content did per Bonnie’s last review:

- Adjusted copy on the “Before You Begin” Page (removed mention of Privacy Policy and ToS and emphasized the warning for the user on not closing their browser)
- Rewrote the example letters on the Landing Page to be unique and match the LG
- Updated all CFA/HfLA changes and created a general modular copy for “what is EA”?
- We are still hoping to complete the privacy policy once we have the template
- Removed the copy “take a break” on one of the LG pop-ups

**Comment by sydneywalcoff** [comment]
## Dev accomplishments
- accessibility audit and refactor; the site is now easily navigable using a keyboard or screen reader
- Credits page *will be done by the time Bonnie reviews
- implemented redesigned 404 page
- CfA updates across the site
- implemented redesigned FAQ page

**Comment by amejiamesinas** [comment]
Research
- content terminology, 
- aligned project-research scope, 
- getting all teams updated on current expungement all in CA

**Comment by anitadesigns** [comment]
## Design Accomplishments 
- Adjusted the illustrations on the landing to improve readability and quality of the pictures which included:
   - Image under "Making letter writing less intimidating" now readable and no longer blurry 
   - Text in Letter examples illustrations are now one color instead of two different colors 
- Designed the Credits page and added a filter view for icons and illustrations and all 
- Designed the 404 page 
- Designed a loading page design 
- Added "credits page" to footer 
- Redesigned the FAQ page 
- Made instructions for user to keep browser open more prevalent on the Before you begin page
- Added an error prevention modal at the of the letter generator to allow user flexibility in downloading the letter or returning home and erasing data. 

## Requested Feedback 
- What is your experience/first impressions of the last modal before the user officially exits the letter generator?
- For FAQ page, how easy is it finding information? Experience using the accordions?
