### ISSUE TITLE
update github.io to work (with new expunge-assist name)

### ISSUE THREAD

**Issue by aahvocado** [hackforla/expunge-assist#208]
The github.io page was broken from the repo name change, so now we can fix it. It seems like the new url is https://hackforla.github.io/expunge-assist/ and is resulting in some 404s
![Screen Shot 2021-04-08 at 6 13 32 PM](https://user-images.githubusercontent.com/2266545/114114688-34021480-9896-11eb-83bf-fb00bb1875d5.png)

There is probably some config/build pointing towards `/record-clearance`

**Comment by alexchoiweb** [comment]
Great success, CI/CD github Action is now functional again on push to `master`: https://hackforla.github.io/expunge-assist/

The initial problem was the project name change, as Daniel Xiao detailed above. This was fixed by updating the `homepage` value in `package.json`

Next the build process failed due to eslint/console warnings so I went ahead and cleared those

With the build able to compile successfully, the Action moved onto the Publish step where it failed due to the owner of the current `secrets.PERSONAL_ACCESS_TOKEN` (Daniel Lee) being recently removed from the admins and maintainers groups so the Action was no longer authorized to publish. Daniel's github account has since been added back to both groups and that fixed that.

Notes for the future: We can move forward with this workflow as long as Daniel Lee's github account remains in the admins/maintainers group. For the future if we would like to rotate in an active contributor's account instead, that account should be added to the admins/maintainers groups and then they would have to update the github project Settings>Secrets with a Personal Access Token generated by their own account. Or, there might be a way to add for multiple tokens at the same time - but i have not tested this

Thanks goes to @ggrrettcchhenn for the assist. We can also add back the required review for `master` branch but for active contributors from the group
