### ISSUE TITLE
create the download page

### ISSUE THREAD

**Issue by aahvocado** [hackforla/expunge-assist#262]
https://www.figma.com/file/t1lW4Tm0Lp3jFdeOCd98b1/Expunge-Assist?node-id=805%3A5554

there is some discussion on whether we are actually going with download/email so this will just be to build out the page

**Comment by ggrrettcchhenn** [comment]
instead of "send in an email" we would like to have the top button be either "copy to clipboard" or "share." The share functionality would be to 1) copy text, 2) email, or 3) text.

@Andan-Eddy @TierneySadowski could we please update the Figma prototype to reflect the editable output option? (I'm thinking Share makes the most sense.)

**Comment by qooqu** [comment]
Looks like we **can** put a body in a mailto link!
https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks#e-mail_links

**Comment by qooqu** [comment]
FYI I have an extremely rough version of the email option working.
