### ISSUE TITLE
Declaration Letter Structure

### ISSUE THREAD

**Issue by apurvabarve** [hackforla/expunge-assist#275]
### Overview
We need to determine the structure of the declaration letter that comes out of the web app.

### Action Items

- [x] Please do some discovery research to determine the structure and order of information @yumengluo @myrandi @LarisaGav 
- [x] Write out questions for each section of the letter @apurvabarve @yumengluo @LarisaGav @myrandi 

### Resources/Instructions
[Sample letter](https://roadmap.rootandrebound.org/understanding-cleaning-up-your-criminal-record/expungement-appendix/sample-declaration/)

[Pro Bono institute](https://docs.google.com/document/d/1iErDXfJ2J68uU_gxTc8Ox5yEC2yE_O5iF0gyeTneAY8/edit)

[CR-180 Petition for Dismissal](https://www.courts.ca.gov/documents/cr180.pdf) (expungement petition)

[MC-031 Attachment form for declaration letter](https://www.courts.ca.gov/documents/mc031.pdf)

[Declaration letter structure recommendations](https://docs.google.com/document/d/1ots_RyutaEkwOYAd8CYy-24mwjcZLi84oxAkatmN5oY/edit?ts=60ccef64#)

[Add your questions and statement responses here](https://docs.google.com/document/d/1nG1oRrkkrpRPCnKnW18zXb6w-ClTVr0-c9YURzYt2io/edit#heading=h.vybgdsrsvj8m)

**Comment by yumengluo** [comment]
1.  the conviction----can be filled up by the lawyer.
2. the cause of conviction--can be filled up by the lawyer. They can help to memorize more details if they want...
3. what they have done since then to improve their life or correct their behaviors... This section can be divided into two parts: personal behavior (stopped drinking, drug), mindset vs public evolvement (school, community services, recovery program)
4.  motivations to clear the record. We can add several categories for them to keep organized. for example, Family: he/she is a parent now and want to provide a better life for the kids.... Career: find a more stable job. Health: a healthier life style now Society: be a more responsible citizen.....

**Comment by LarisaGav** [comment]
[Statement Structure.docx](https://github.com/hackforla/expunge-assist/files/6642470/Statement.Structure.docx)

**Comment by myrandi** [comment]
[Proposed declaration structure](https://docs.google.com/document/d/1ots_RyutaEkwOYAd8CYy-24mwjcZLi84oxAkatmN5oY/edit)
