### ISSUE TITLE
Content writing review of frame #49 of Mobile Prototype

### ISSUE THREAD

**Issue by Andan-Eddy** [hackforla/expunge-assist#362]
### Overview
Content writing review of design changes made to Frame #49  (step 5 finalize) of Mobile Prototype. 
https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=2%3A4

### Action Items
Perform content writing review of Frame #49  (step 5 finalize) of Mobile Prototype. Including grammar, structure consistency......

### Resources/Instructions
https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=2%3A4

**Comment by SamHyler** [comment]
see slack thread

**Comment by SamHyler** [comment]
Review @Andan-Eddy 

**The biggest priority before MVP**:I want to make changes to the copy on the first screen/page and rewrite it (I want to change all the copy on all of those pages for each section - too many exclamation points and wrong tone. The ones that say for example "hooray"), **happy to do that now if I have the greenlight.** 

The button “looks good” might be better as something else like “done” or “finish” since looks good is a little bit leading on how the user should feel about things (maybe it doesn’t look “good” but just “enough” or “eh”). I fixed a couple of commas, and there were errors in the letter (maybe was intentional? - this will also change soon when Lori & I are done with reworking the declaration letter questions). Some details like Headlines I would want to do a sweep of everything to check for consistency, but I would do that a little later on once the guidelines have been reviewed and approved.

**Comment by Andan-Eddy** [comment]
met with @SamHyler gave green light to make changes to the copy on first scree/page before the MVP lauched

**Comment by SamHyler** [comment]
Should we close this issue now?

**Comment by Andan-Eddy** [comment]
yep
