### ISSUE TITLE
Rewrite opener screens for mobile & desktop

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#390]
### Overview
Rewrite copy for the mobil and desktop screens before each question section begins (Existing copy starts with 'well done!' or "hooray!"or "Fabulous" for example, has a picture of a person at a computer on them).

This copy is to be included in the MVP launch.

### Action Items
- [x] Rewrite copy
- [x] Update and create consistent tone of voice
- [x] Pass over to Development to add to the MVP version of the product  (see issue https://github.com/hackforla/expunge-assist/issues/404) 

### Resources/Instructions
Copy is in [this](https://docs.google.com/document/d/12cTlPhxR_nPym6OcsMfnYtsRlVAW7jYH29wHp9Mvg5I/edit) document.
Mockups in Expunge Assist Main Figma under [content tab](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=2%3A5).

**Comment by ExperimentsInHonesty** [comment]
Hi @SamHyler @westphll 

This issue is in the prioritized backlog and is assigned to you both and seems complete.  
1. Issues in the prioritized backlog should not be assigned to anyone
2. Issues in the prioritized backlog should be ready to be worked on and labeled for the type of role that needs to work on it.
3. Issues should be able to be closed when the person working on them is done, instead of never closing.

I recommend creating separate issues for each page that you want changed, and that way they get the label for that page.  You can work with Dev or Product to make these issues, or you can make them yourself when you are ready to do the handoff.  That will enable you to close this issue.
