### ISSUE TITLE
Change name of "We're looking for Partners to Help" section of Landing Page on Figma

### ISSUE THREAD

**Issue by Andan-Eddy** [hackforla/expunge-assist#437]
### Overview
Change name "We're looking for Partners to Help" section of Landing Page on Figma to "Partnership Goals". The bullet in the section should also be changed. 

### Action Items
- [ ] Change name "We're looking for Partners to Help" section of Landing Page on Figma to "Partnership Goals"
- [ ] First bullet should be changed to read: "Our first product a personal statement generator will help streamline filing criminal record expungement."
- [ ] Second bullet should be changed to read: "We will work with Partners to refine products to fit the needs of your organization"

**Comment by Andan-Eddy** [comment]
Daisy is redesign landing page- this section will be changed. Check with Daisy about how this section will be integrated. Mahmoud will follow up on this

**Comment by jamiesiu** [comment]
Closing this out as "Won't Do" since the current landing page section related to this already advanced to a different iteration currently as
`**Partnership Opportunities**: Expunge Assist is currently looking for partner organizations to refine and tailor the product to the needs of their organizations. Reach out to learn more. `

This issue here is out of date. Can re-open if needed.
