### ISSUE TITLE
[PAUSE STUFF] Update and sync all button copy across product/design system [Design/Content system stage 2]

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#631]
### Overview
Update the Design system by adding all buttons throughout the product to distinguish which copy goes where. 
This is a next step in updating the content in the design system and syncing across product.

### Action Items
- [x] Review all buttons and discover inconsistencies and areas for improvement. Find all distinguishable buttons and make a list/categories
- [x] Flag button copy to be changed/discussed/reviewed
- [ ] Update and sync all buttons
- [ ] Create a separate source of truth document for all button copy
- [ ] Be sure all are synced and up to date across product
- [ ] Update any button copy necessary and handover to Dev if there are changes

### Resources/Instructions
[Design system page in figma](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=2%3A2)

**Comment by emmathrash** [comment]
Created an audit table in Figjam with visual notes too. Awaiting conclusion of V&T exercise before finalizing any necessary content changes

**Comment by emmathrash** [comment]
Updated the action items to separate the design system and content source of truth. Design will create the button components in Figma but content will create a separate document to house the copy.

**Comment by anitadesigns** [comment]
Once we have our tone finalized, Design wants to finalize the button style on our website. Justin and I had an idea of decreasing the buttons radius so it's more rectangular than oval. Before making this change, we want to ensure that it would compliment the overall tone. I created an issue for Design to work on this once branding is done. Since we are collaborating on the buttons, I'm assuming this issue would be dependent on #1129 since we would replace all buttons across our wireframes and may need Content's review to ensure the copy across the buttons are correct? @SamHyler @emmathrash

**Comment by SamHyler** [comment]
Curios on progress on this issue. Do we need discussions to finalize? I see you mention tone @anitadesigns. Let us know what needs there are so we can finish this one! @emmathrash @jyehllow  for reference.
