### ISSUE TITLE
List privacy policy in FAQs

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#658]
### Overview
Notes from this issue https://github.com/hackforla/expunge-assist/issues/231 - Dev would like the Privacy Policy listed in the notes. 
### Action Items
- [ ] Find an appropriate place to list privacy policy in FAQs
- [ ] Add it
- [ ] Discuss in content / design
- [ ] hand over to dev

### Resources/Instructions
See notes from this issue https://github.com/hackforla/expunge-assist/issues/231

**Comment by jamiesiu** [comment]
Some notes to add: this ticket is more about refining the privacy policy content/copy after Product updates the Privacy Policy as part of #231. The location and availability of Privacy Policy information is already being addressed by the current footer updates by Design team as well as the LP update/reorganization of sections which would highlight the Privacy Policy. This is not urgent for IUT2 as it doesn't blocker user testing, but should be done prior to wider target user testing.

**Comment by SamHyler** [comment]
closing as this hasn't been followed up on in a year
