### ISSUE TITLE
Update Categories page

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#701]
### Overview
From this [issue](https://github.com/hackforla/expunge-assist/issues/597)
Update categories page

### Action Items
- [x] Change copy, reorder flow
- [x] Add Check box and "Something else" copy

### Resources/Instructions
[Design hand off space](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=6099%3A63207)

**Comment by anitadesigns** [comment]
@aahvocado @sydneywalcoff Handing over this issue to you. I want to highlight that it is connected to Issue #698 because it includes adding "Something else" as the last category/option on this page.  @SamHyler sent a message on Slack regarding Issue #698 and the feasibility of IUT2. Re-arranging the order of the other categories and changing the copy of some of those titles is not dependent on Issue #698
