### ISSUE TITLE
[PAUSE STUFF] Source of truth for Content on Figma

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#757]
### Overview
Using figma as the source of truth is unstable and tracking between so many screens is extremely time consuming and subject to human error in its current state. We need to troubleshoot and find a better method, whether it be using external tools or finding a better way within Figma. 
Sometimes, what Content finalizes does not end up in the final Designs or does not appear on the live site in the same way. These problems need troubleshooting as well.  

### Action Items
- [ ] Troubleshoot problem areas
- [x] Research external tools and other solutions https://github.com/hackforla/expunge-assist/issues/865
- [ ] Explore Figma components and their capabilities. Can this assist in the source of truth? how?
- [ ] Discuss in Content and Design
- [ ] Decide on a new method of working with source of truth
- [ ] Make decisions about Contentful and update Dev with our solution/choices

### Resources/Instructions
Use Google docs and Figma to document your ideas, iterations, frustrations, and solutions, and link them here under resources.

**Comment by SamHyler** [comment]
Ditto is being tested now

**Comment by lexramos01** [comment]
Hi @SamHyler - I had an idea/solution for the Source of truth. I was looking at a couple of Dev hand-off resources and found that folks use Figjam and Miro to collaborate on quick sketches, flows, and "markups" to outline and discuss decisions. It made me think: Are we underutilizing Figjam? 

Here is the thought I had: 

- What if we start to use Figma as the Source of Truth and use Figjam as our brainstorming / building content section? The method can look something as follows: Figjam will be the primary area where the Content team works to brainstorm and finalize content ideas. Then, when things are approved / finalized, it moves to the regular Figma area where it lives solely for dev handoff and for Source of Truth purposes. The rule could be that **nothing** gets edited when it moves to Figma - Content can only propose edits for approval in Figjam. 
- Editing in Figjam can ensure we're:
1.  collaborating with each other
3. controlling when and why things get editing in Figma

Let me know your thoughts and happy to discuss further at our next content meeting!

**Comment by SamHyler** [comment]
> Hi @SamHyler - I had an idea/solution for the Source of truth. I was looking at a couple of Dev hand-off resources and found that folks use Figjam and Miro to collaborate on quick sketches, flows, and "markups" to outline and discuss decisions. It made me think: Are we underutilizing Figjam?
> 
> Here is the thought I had:
> 
> * What if we start to use Figma as the Source of Truth and use Figjam as our brainstorming / building content section? The method can look something as follows: Figjam will be the primary area where the Content team works to brainstorm and finalize content ideas. Then, when things are approved / finalized, it moves to the regular Figma area where it lives solely for dev handoff and for Source of Truth purposes. The rule could be that **nothing** gets edited when it moves to Figma. Content can only propose edits for approval in Figjam.
> * Editing in Figjam can ensure we're:
> 
> 1. collaborating with each other
> 2. controlling when and why things get edited in Figma
> 
> Let me know your thoughts and happy to discuss further at our next content meeting!

I wrote this on Slack already but copying here so we have a record of discussions around finding the SOT for the future documentation of the project:

Thanks for this, Alexis! Let’s talk about it at the next Content meeting. I see where you’re going with this thought. I’m curious if Figjam is as robust for the Design side of things, or if we can only use it for something like wireframing high or low fidelity.
I’m unsure if it will work because I think it might have a similar effect to how we are doing it now (making mockups on Figma and then finalizing them). The issues typically happen in 1. Content’s own human error 2. The ongoing reworking Figma to the new format and thus having at least 3 spots to maintaining the SOT (2 master’s and an iteration page, and the hand over space sometimes as well gets in the mix) that we began summer 2022 and 3. Human error when Design copies the text between iterations or to the final space. Sometimes it’s a mystery how the SOT gets changed, but it’s a lot of human error either way. It might be a good idea though to have something that isn’t Figma be the SOT since it’s hard to track changes on Figma. On google docs for ex you can see the history with exact markups with each person’s name so you can see what happened more easily.
I really appreciate the input, slowly we will get there!

I'll also add it might make it harder to collaborate with Design, or maybe not. Looking forward to discussing it further!

**Comment by lexramos01** [comment]
FYI for Ditto - 

The more I look at Ditto, the more I think it could be the solution. The only problem is with testing because I'm coming up with this error pop-up when I try to test Ditto in Figma. 

<img width="669" alt="Screen Shot 2023-06-11 at 5 07 16 PM" src="https://github.com/hackforla/expunge-assist/assets/125330986/2cf55cd9-b257-47ed-bded-5c48aad2dcbb">

**Comment by lexramos01** [comment]
**Ditto notes**
Benefits

- Variants in Ditto allow teams to write and preview text variations for frames in their projects. You can use variants for localization, state-based text, and explorations. This could be beneficial when content works on the letter generator for different user segments. [Learn More](https://www.dittowords.com/docs/variants)
- Components in Ditto are text items that get synced across projects and allow teams to standardize and reuse text. Commonly created components include: Taglines and descriptions, Error messages, CTAs
- You can edit text items that are in a nested Figma component instance
- Sync edits to other duplicates in a project and then componentize them so that as future edits will sync up in the future

**Drawbacks**

- Current account is set up under The Starter Plan. The Starter Plan is limited to 4 users per workspace. This could limit the amount of collaboration being achieved if the Content Team grows to 4+. If we have everyone signed into Ditto using the EA email, this will limit our collaboration in terms of tagging each other (we won't be able to tag individuals if everyone is using the EA email). 
- There may be a learning curve to fully understanding and integrating Ditto into this project

**Comment by lexramos01** [comment]
@SamHyler I had a new idea for source of truth that I welcome your thoughts on: 

When working on a new issue that required content brainstorming (writing new copy, etc), content uses Google Docs instead of Figma. This ensures:
- collaboration (content team members can tag others to proofread, review, give feedback on copy) 
- Google docs allows you to see the history of changes done
- a history of the work being done for future volunteers

Once new copy is established approved by the content lead, move the approved content into Figma for Design handover. This allows: 

- All content with copy in Figma is approved content (source of truth) 
- Content drafts are kept separate from Figma

**Comment by SamHyler** [comment]
@lexramos01 Thanks for all your work and thoughts on this! 

Thank you for notes on both Ditto and Gdocs! Really helpful, thank you for thinking this sticking point through. 

All good ideas. 
My concern with working in Google Docs is that it would inhibit collaboration with Design, which is important. I do see how it facilitates better collaboration within Content though. 
The other issue I see happening (because it happened before), is the copy/paste from GDocs to Figma could add human error and there would be two SOTs to sort through.

I have heard that some content folks use copy docs, essentially huge excel files where they keep the SOT for each and every string and it's location. Honestly that sounds stressful, but if something like this is the only way... ?

What do you think?

We can always test something on a smaller scale and see how the SOT and collaboration function. That's one way of knowing how it works and what team members prefer?

**Comment by SamHyler** [comment]
Hey @lexramos01 ! Thanks for all the thoughts and work here. Sorry I didn't reply earlier about Ditto, what you noted here is really helpful as we think through and test options for the SOT. Thanks for the notes on both, really helpful. 

I can see why you suggest using Google Docs. My concern with using docs is the following (mostly because we started using this method at EA when Content was established so there is some experience in how it worked)
- decreased collaboration with Design or no collaboration at all until the last minute, decreased transparency between teams. potential "content last" approach that moves away from our goal of "content first" approach
- difficult to see the content in context of the wireframes/prototypes (for i.e. character could, hierarchy, or visual aspects)
- potential for two SOT's to emerge (gdoc and figma)
- potential human error in transferring the text and strings over

I've heard there are content teams that use copy docs, essentially excel files/sheets that contain every single string and its location. We could do this, but it sounds honestly stressful. 

We can always test this method using google docs on a smaller scale so that we have some feedback on the problems. What do you think?

**Comment by SamHyler** [comment]
Great, I retyped my comment because my computer crashed. But both appeared ;-) Ah, technology.

**Comment by lexramos01** [comment]
Hi @SamHyler - i really like the idea of doing a copydoc. I'll explore this further!

**Comment by lexramos01** [comment]
Update: Found this helpful article re: copy docs. [https://www.frontitude.com/glossary-posts/what-are-copy-docs#:~:text=A%20copy%20doc%20is%20a%20shared%20file%20that%20helps%20you,the%20text%20throughout%20the%20process.](https://www.frontitude.com/glossary-posts/what-are-copy-docs#:~:text=A%20copy%20doc%20is%20a%20shared%20file%20that%20helps%20you,the%20text%20throughout%20the%20process.)

I will create a copy doc for one of the latest project's we've closed on the Before you begin issue and follow up.

**Comment by lexramos01** [comment]
Link to copy docs example: [https://docs.google.com/document/d/1559nfVeQSJgwgpPpew_r0i4VH74dPHLS/edit?usp=sharing&ouid=109790522493582940810&rtpof=true&sd=true](https://docs.google.com/document/d/1559nfVeQSJgwgpPpew_r0i4VH74dPHLS/edit?usp=sharing&ouid=109790522493582940810&rtpof=true&sd=true)

**Comment by lexramos01** [comment]
Another option is we can update the content on our own: https://github.com/hackforla/expunge-assist/wiki/Updating-Content

**Comment by SamHyler** [comment]
Decided on trying a copydoc for the source of truth going forward in [this issue](https://github.com/hackforla/expunge-assist/issues/1044). Closing issue as explorations here are finished
