### ISSUE TITLE
Letter generator: Involvement section crashing depending on the order of your answers

### ISSUE THREAD

**Issue by jamesshin27** [hackforla/expunge-assist#843]
### Overview
In the letter generator, there is a bug where the website gets stuck on a white landing page if the answers are chosen in a specific order. We were able to reproduce the same situation with a few different orders of choices although we haven't identified them all yet.

**Example**

Job option is selected
![Screenshot 2023-02-16 at 10 28 10 AM](https://user-images.githubusercontent.com/120442577/219455247-4769768c-8d99-40f5-b2c0-9b102235bd52.png)
User is directed to this page after pressing next
![Screenshot 2023-02-16 at 10 29 30 AM](https://user-images.githubusercontent.com/120442577/219455522-26c000a8-5ebb-41ba-9a45-dd118b0a591a.png)
I pressed the back option to choose the recovery option as well
![Screenshot 2023-02-16 at 10 29 54 AM](https://user-images.githubusercontent.com/120442577/219455618-59d5e4a1-79f6-4efe-b323-3691d79e5e24.png)
Users can continue to fill out the next two screens
![Screenshot 2023-02-16 at 10 30 49 AM](https://user-images.githubusercontent.com/120442577/219455802-8a1afbf4-afd1-449a-8029-a65651df0538.png)
![Screenshot 2023-02-16 at 10 31 20 AM](https://user-images.githubusercontent.com/120442577/219455897-ac51be72-4633-46ab-89ad-c35c89b110e5.png)
When you press next, you get stuck on this white landing page
<img width="1582" alt="Screenshot 2023-02-16 at 10 23 45 AM" src="https://user-images.githubusercontent.com/120442577/219456229-bcd36a6d-aa37-4d84-a44e-791747516036.png">

### Action Items

- [ ] Look into why this specific order of choices ends up with the white blank landing page

### Resources/Instructions
Please refer to the screenshots provided for context.

**Comment by anitadesigns** [comment]
I also am experiencing the same bug when I select Job and Recovery or just Recovery. However, if I select Recovery and any other option that lies underneath (Education - None of the Above) then it bypasses that blank page and goes to the "Future goals" section. 

**Here is a breakdown of selecting "Recovery" and "Education"**

1. Selected "Recovery" and "Education"
![Screen Shot 2023-02-16 at 12 05 45 PM](https://user-images.githubusercontent.com/105686896/219475086-0f77049b-36ff-476a-a189-a8f91c09959d.png)

2. Directed to unemployed although "Unemployed/none of the above" WAS NOT selected 
![Screen Shot 2023-02-16 at 12 08 39 PM](https://user-images.githubusercontent.com/105686896/219475777-723d5e06-c61e-4fab-b549-715744b5848c.png)

3. Directed to Unemployed preview and edit page
![Screen Shot 2023-02-16 at 12 10 42 PM](https://user-images.githubusercontent.com/105686896/219476325-cab629aa-b001-4a5c-9bb1-acc83a99e8a4.png)

4. Finally directed to the Recovery page 
![Screen Shot 2023-02-16 at 12 11 24 PM](https://user-images.githubusercontent.com/105686896/219476442-9822ca8f-f232-4205-be4c-8aa1476d9f56.png)

5. Recovery preview and edit page AND Education page are skipped and directed to the Future goals section
![Screen Shot 2023-02-16 at 12 13 14 PM](https://user-images.githubusercontent.com/105686896/219476716-f3577e70-1d3e-4ba0-88f3-c7511e882439.png)

❗️FYI: This only happens when "Recovery" is selected with another option such as "Education"  and "Parenting" . When "Recovery" and "community service" are selected together, the recovery page is present (without the preview and edit page in that flow) and then directed to "community service" 


Looks like the Recovery preview and edit page is missing and may be the reason the letter generator does not proceed when a user selects "Job" and "Recovery"
