### ISSUE TITLE
Team Review of Information Gathering Survey (Google Form)

### ISSUE THREAD

**Issue by kelseylondon** [hackforla/expunge-assist#847]
### Overview
We have received approval to carry out the Information Gathering Survey, originally developed in Summer/Fall 2022. To (re-)familiarize ourselves with plans for this survey, we need all team members to (1) review the survey and (2) provide feedback and suggestions.

### Action Items

- [ ] Review [the Information Gathering Survey](https://docs.google.com/forms/d/1D-sv63VENV_mutBHWKuxC5P33pGAmDoYZapdZIC9fnw/edit)
- [ ] Please provide feedback and suggestions on the survey itself _as a comment to this issue._ 
- [ ] Once you have completed the above steps, please check off your name below:
   - [x] Yumeng
   - [ ] Kelsey
   - [x] Sam
   - [x] Kevin
   - [x] Sofia
   - [ ] Analicia
   - [ ] Travis

### Resources/Instructions
- [Information Gathering Survey](https://docs.google.com/forms/d/1D-sv63VENV_mutBHWKuxC5P33pGAmDoYZapdZIC9fnw/viewform?edit_requested=true)
- [Research Plan 1: Information Gathering Survey](https://docs.google.com/document/d/1HTzlBNJ304NfD9stoEhjfrrVg0KD2Qbm2gkVUJM7KUM/edit)
- [RP1 wiki page](https://github.com/hackforla/expunge-assist/wiki/Research-Plan-1:-Information-Gathering-Survey)
- [Research Timeline](https://github.com/hackforla/expunge-assist/wiki/Expunge-Assist-Research-Plans-and-Goals)
- [RP 1 Google Drive folder](https://drive.google.com/drive/folders/15lFLxUEEQ8JFSFrWwNC4YAkwSO5OYyto)

### Related issues
- #846 
- #728 
- #714 
- #652

**Comment by sofialaguna** [comment]
Suggestions for survey:

- I suggest deleting the first sentence in the second paragraph of the survey introduction because it confusing. The paragraph does not explain what the personal document is or why the terms are important until you read the next sentence. Starting with the second sentence will make more sense.
- Add a sentence at the end of the introduction stating something like, "Your response to this survey is confidential. If you do not enter the optional contact information below, your response will be anonymous."
- For the first question (What is your profession?), add response options for "I am a law clerk" and "I am a legal assistant"
- In question 3, add a (s) in "In which state(s)" because some legal professionals work in multiple states.
- In question 4, add "Optional:" before listing the question so it flows rather than adding the note in parenthesis at the end.
- In question 5, add an (s) after criminal record (some clients may have multiple). 
     - In the response options for question 5, add "Not Applicable" as an option for attorneys who do not do expunge work.
 
Everything else looks great!

**Comment by kevinmoutoucarpin** [comment]
> If you answered "Yes" or "Sometimes/It's optional" above, what do you usually call this document?

For this question, I would remove "usually" and keep the rest that way or replace it with "most commonly"
