### ISSUE TITLE
Follow up - Review Mobile Wireframes (Content)

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#885]
### Overview
Alexis reviewed the mobile wireframes https://github.com/hackforla/expunge-assist/issues/844 and found the following error:

In the last flow "Download"

The Mobile Wireframe appears more accurate than in the Desktop Master Page. Text "Previewing Final Letter" in the Master Page does not match up with the text of previous flows and has the word "test" in it as well.

### Action Items

- [x] Review error and fix

**Comment by kyle-whitaker** [comment]
Alexis is right, some content is more up to date in Mobile version; other parts are less clear, Added to 3/30 content meeting agenda to discuss. Will make decisions in meeting and close issue.

**Comment by kyle-whitaker** [comment]
Differences found between Desktop Master and Mobile WIP:
- "Previewing final statement" in Desktop rather than "letter" as in Mobile (fixed)
- Sample letter in Desktop is older version than in Mobile (fixed)
- Info/Review your completed declaration letter box copy doesn't match; Mobile has extra first sentence ("Your declaration letter is now complete.") & lacks "with a text editor such as" language; Mobile also says "Microsoft Docs" instead of "Word"
- Desktop & Mobile both have the same liability language, but it doesn't match the live site; they include a recommendation to consult a lawyer (live site doesn't), and they use "personal statement" (live site says "letter")

**Comment by SamHyler** [comment]
All comments Kyle mentioned above are fixed. https://github.com/hackforla/expunge-assist/issues/928
