### ISSUE TITLE
[Updating Content Guidelines]  "Fresh start" Concept and framing EA's work

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#907]
### Overview
How do we describe EA's work to the public?

Investigate the concept of “fresh start” and "second chance" (i.e. clearing one's record gives on a fresh start or second chance at life) and how to describe EA’s work. 
### Action Items

- [x] Investigate the two concepts, "second chance" and "fresh start." What is useful/problematic about them? Do they fit our tone of voice and audience/user group(s)? Could they be offensive or pedantic? 
- [x] Review language on the Landing page, about us page, FAQs, and on for example HfLA's Expunge Assist page. 
- [x] Look in the Google Drive for any marketing type materials, check out the EA "One page" and any other documents with an "about what we do at EA" type feel
- [x] Compile these examples and review. Which language fits best, which doesn't? 
- [x] Do any documents of text on any site/page need to be reviewed/changed, or archived? 
- [x] Can we create one "statement" or small segments of how we describe what we do at EA? 

- [x] Recommend terms to use for this project 

### Resources/Instructions
[Concepts Investigation Doc](https://docs.google.com/document/d/1AY-TSIGeeVBlF5pVU94tlFUgmiVMa0t9ZOOqoctW4OA/edit?usp=sharing)
Content Guidelines on Figma
Google Drive - marketing materials, etc
HfLA's homepage with EA project
Other Figma pages (landing page, about us page)

**Comment by lexramos01** [comment]
Hi @SamHyler - I created a Strengths/Weaknesses diagram in Figma under our Writing/Content Guidelines. Highlighted [here](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=2%3A19&t=TxN7bYnVb84O1syR-1).

A quick summary of my findings below: 

- “Second chance” ignores that actual lives and communities have been decimated by inequitable laws, rabid police officers, overzealous prosecutors, racially homogenous juries and intolerant judges. (source: [https://standtogethertrust.org/stories/the-importance-of-second-chances-in-our-justice-system/](url)
- "Fresh start" could imply that the user WILL have a fresh start. There is a rule in our Writing/Content Guidelines that we should avoid.  “DON’T say: “This tool can help you achieve expungement and feel better by moving on with your life.” This version implies that they WILL achieve expungement and that they WILL feel better, and they WILL move on with their life” Source: [Writing/Content Guidelines ](https://docs.google.com/document/d/1w8iHLEjgBlkwi6jm7XgLoI0RE3JtmUnJtCq3psks1nI/edit?usp=sharing )

- I reviewed language on the Landing page, about us page, FAQs, marketing materials "one page" and the design/brand guide presentation. I left some notes on what I thought worked well and what did not and my reasoning behind it. My main thought was if we should consider changing phrases that use the words "people with criminal records". Even though “people with criminal records” is not categorizing or labeling a person, I wondered if the term “criminal” may be a trigger or cause users to think in the logic of "I have a criminal record, therefore I am a criminal." We use the phrase "justice impacted individuals", which works better and is referenced in other sources on trauma-informed language. 

- I pulled together segments of words / sentences that worked and added them to the diagram as well. I think it's definitely possible to pull from here in order to create a sentence that describes what EA does.
