### ISSUE TITLE
Progress Bar Bug

### ISSUE THREAD

**Issue by AilinLuca** [hackforla/expunge-assist#945]
### Overview
When you navigate between[ Introduce Yourself,](https://expungeassist.org/#/./form/introduction/preview), [Involvement](https://expungeassist.org/#/./form/involvement), and [Employment](https://expungeassist.org/#/./form/job), the progress bar jumps ahead and then moves back in a way that doesn't seem to make sense. 

If you add 3 options in the Involvement section, the progress bar doesn't move at all when you reach Employment.

If you select 4 or more, it goes back once you reach Employment.

### Action Items
- [ ] Fix progress bar so it reflects actual progress.

### Resources/Instructions
- Navigate site here: https://expungeassist.org/

**Comment by davidwiese** [comment]
Quick update:

Finally been able to dig a bit into this issue. I've narrowed down where the problem is occurring in `FormHeader.tsx` - it specifically has to do with the `percentageComplete` calculation, and how the checkboxes affect the maxNum in the calculation. 

When multiple (4+) selections are checked on the Involvement page, it increases the maxNum too much, so the result of the calculation `(stepNum / maxNum) * 100` actually decreases between steps. If only 3 are selected, the math shows no change in the `percentageComplete`. If 1 or 2 are selected, it behaves pretty much how you would expect.

I considered just having a static value for `percentageComplete` depending on which page of the form the user is on, but that order is determined by which boxes are selected on the Involvement page so it isn't so straightforward. Will continue to troubleshoot.

**Comment by davidwiese** [comment]
Further testing on the Involvement page shows a few things:

1. Each checkbox increases the `stepNum` from 2 to 3, _except_ the `Self-improvement` box which increases `stepNum` to 4 if selected by itself. Otherwise if it is selected with another box the `stepNum` still only goes up to 3.
2. Each checkbox increases the `maxNum` by 1 -- with all boxes checked, this value is 13.
